apiVersion: v1
kind: Service
metadata:
  name: {{ include "webhookx.fullname" . }}
  labels:
    {{- include "webhookx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.proxyPort }}
      targetPort: proxy
      protocol: TCP
      name: proxy
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "webhookx.selectorLabels" . | nindent 4 }}
